import FreeCAD, Part, FreeCADGui
doc = FreeCAD.newDocument("Professional_Model")
# Create floors
floor_thickness = 150
living_room_floor = doc.addObject("Part::Box","Living_Room_Floor")
living_room_floor.Length = 6000
living_room_floor.Width = 4000
living_room_floor.Height = floor_thickness
living_room_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,0),FreeCAD.Rotation(0,0,0))
bedroom1_floor = doc.addObject("Part::Box","Bedroom1_Floor")
bedroom1_floor.Length = 4000
bedroom1_floor.Width = 3000
bedroom1_floor.Height = floor_thickness
bedroom1_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,0,0),FreeCAD.Rotation(0,0,0))
bedroom2_floor = doc.addObject("Part::Box","Bedroom2_Floor")
bedroom2_floor.Length = 4000
bedroom2_floor.Width = 3000
bedroom2_floor.Height = floor_thickness
bedroom2_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,4000,0),FreeCAD.Rotation(0,0,0))
kitchen_floor = doc.addObject("Part::Box","Kitchen_Floor")
kitchen_floor.Length = 3000
kitchen_floor.Width = 3000
kitchen_floor.Height = floor_thickness
kitchen_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(0,7000,0),FreeCAD.Rotation(0,0,0))
bathroom1_floor = doc.addObject("Part::Box","Bathroom1_Floor")
bathroom1_floor.Length = 2000
bathroom1_floor.Width = 2000
bathroom1_floor.Height = floor_thickness
bathroom1_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(5000,0,0),FreeCAD.Rotation(0,0,0))
bathroom2_floor = doc.addObject("Part::Box","Bathroom2_Floor")
bathroom2_floor.Length = 2000
bathroom2_floor.Width = 2000
bathroom2_floor.Height = floor_thickness
bathroom2_floor.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,4000,0),FreeCAD.Rotation(0,0,0))
# Create walls
wall_thickness = 200
living_room_wall1 = doc.addObject("Part::Box","Living_Room_Wall1")
living_room_wall1.Length = 6000
living_room_wall1.Width = wall_thickness
living_room_wall1.Height = 3000
living_room_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,floor_thickness),FreeCAD.Rotation(0,0,0))
living_room_wall2 = doc.addObject("Part::Box","Living_Room_Wall2")
living_room_wall2.Length = wall_thickness
living_room_wall2.Width = 4000
living_room_wall2.Height = 3000
living_room_wall2.Placement = FreeCAD.Placement(FreeCAD.Vector(6000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
living_room_wall3 = doc.addObject("Part::Box","Living_Room_Wall3")
living_room_wall3.Length = 6000
living_room_wall3.Width = wall_thickness
living_room_wall3.Height = 3000
living_room_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(0,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
living_room_wall4 = doc.addObject("Part::Box","Living_Room_Wall4")
living_room_wall4.Length = wall_thickness
living_room_wall4.Width = 4000
living_room_wall4.Height = 3000
living_room_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom1_wall1 = doc.addObject("Part::Box","Bedroom1_Wall1")
bedroom1_wall1.Length = 4000
bedroom1_wall1.Width = wall_thickness
bedroom1_wall1.Height = 3000
bedroom1_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom1_wall2 = doc.addObject("Part::Box","Bedroom1_Wall2")
bedroom1_wall2.Length = wall_thickness
bedroom1_wall2.Width = 3000
bedroom1_wall2.Height = 3000
bedroom1_wall2.Placement = FreeCAD.Placement(FreeCAD.Vector(11000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom1_wall3 = doc.addObject("Part::Box","Bedroom1_Wall3")
bedroom1_wall3.Length = 4000
bedroom1_wall3.Width = wall_thickness
bedroom1_wall3.Height = 3000
bedroom1_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,3000,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom1_wall4 = doc.addObject("Part::Box","Bedroom1_Wall4")
bedroom1_wall4.Length = wall_thickness
bedroom1_wall4.Width = 3000
bedroom1_wall4.Height = 3000
bedroom1_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom2_wall1 = doc.addObject("Part::Box","Bedroom2_Wall1")
bedroom2_wall1.Length = 4000
bedroom2_wall1.Width = wall_thickness
bedroom2_wall1.Height = 3000
bedroom2_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom2_wall2 = doc.addObject("Part::Box","Bedroom2_Wall2")
bedroom2_wall2.Length = wall_thickness
bedroom2_wall2.Width = 3000
bedroom2_wall2.Height = 3000
bedroom2_wall2.Placement = FreeCAD.Placement(FreeCAD.Vector(11000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom2_wall3 = doc.addObject("Part::Box","Bedroom2_Wall3")
bedroom2_wall3.Length = 4000
bedroom2_wall3.Width = wall_thickness
bedroom2_wall3.Height = 3000
bedroom2_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,7000,floor_thickness),FreeCAD.Rotation(0,0,0))
bedroom2_wall4 = doc.addObject("Part::Box","Bedroom2_Wall4")
bedroom2_wall4.Length = wall_thickness
bedroom2_wall4.Width = 3000
bedroom2_wall4.Height = 3000
bedroom2_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
kitchen_wall1 = doc.addObject("Part::Box","Kitchen_Wall1")
kitchen_wall1.Length = 3000
kitchen_wall1.Width = wall_thickness
kitchen_wall1.Height = 3000
kitchen_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(0,7000,floor_thickness),FreeCAD.Rotation(0,0,0))
kitchen_wall2 = doc.addObject("Part::Box","Kitchen_Wall2")
kitchen_wall2.Length = wall_thickness
kitchen_wall2.Width = 3000
kitchen_wall2.Height = 3000
kitchen_wall2.Placement = FreeCAD.Vector(3000,7000,floor_thickness)
kitchen_wall3 = doc.addObject("Part::Box","Kitchen_Wall3")
kitchen_wall3.Length = 3000
kitchen_wall3.Width = wall_thickness
kitchen_wall3.Height = 3000
kitchen_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(0,10000,floor_thickness),FreeCAD.Rotation(0,0,0))
kitchen_wall4 = doc.addObject("Part::Box","Kitchen_Wall4")
kitchen_wall4.Length = wall_thickness
kitchen_wall4.Width = 3000
kitchen_wall4.Height = 3000
kitchen_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(0,7000,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom1_wall1 = doc.addObject("Part::Box","Bathroom1_Wall1")
bathroom1_wall1.Length = 2000
bathroom1_wall1.Width = wall_thickness
bathroom1_wall1.Height = 3000
bathroom1_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(5000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom1_wall2 = doc.addObject("Part::Box","Bathroom1_Wall2")
bathroom1_wall2.Length = wall_thickness
bathroom1_wall2.Width = 2000
bathroom1_wall2.Height = 3000
bathroom1_wall2.Placement = FreeCAD.Placement(FreeCAD.Vector(7000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom1_wall3 = doc.addObject("Part::Box","Bathroom1_Wall3")
bathroom1_wall3.Length = 2000
bathroom1_wall3.Width = wall_thickness
bathroom1_wall3.Height = 3000
bathroom1_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(5000,2000,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom1_wall4 = doc.addObject("Part::Box","Bathroom1_Wall4")
bathroom1_wall4.Length = wall_thickness
bathroom1_wall4.Width = 2000
bathroom1_wall4.Height = 3000
bathroom1_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(5000,0,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom2_wall1 = doc.addObject("Part::Box","Bathroom2_Wall1")
bathroom2_wall1.Length = 2000
bathroom2_wall1.Width = wall_thickness
bathroom2_wall1.Height = 3000
bathroom2_wall1.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom2_wall2 = doc.addObject("Part::Box","Bathroom2_Wall2")
bathroom2_wall2.Length = wall_thickness
bathroom2_wall2.Width = 2000
bathroom2_wall2.Height = 3000
bathroom2_wall2.Placement = FreeCAD.Placement(FreeCAD.Vector(11000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom2_wall3 = doc.addObject("Part::Box","Bathroom2_Wall3")
bathroom2_wall3.Length = 2000
bathroom2_wall3.Width = wall_thickness
bathroom2_wall3.Height = 3000
bathroom2_wall3.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,6000,floor_thickness),FreeCAD.Rotation(0,0,0))
bathroom2_wall4 = doc.addObject("Part::Box","Bathroom2_Wall4")
bathroom2_wall4.Length = wall_thickness
bathroom2_wall4.Width = 2000
bathroom2_wall4.Height = 3000
bathroom2_wall4.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,4000,floor_thickness),FreeCAD.Rotation(0,0,0))
# Create windows
window_width = 1000
window_height = 1500
living_room_window1 = doc.addObject("Part::Box","Living_Room_Window1")
living_room_window1.Length = window_width
living_room_window1.Width = 100
living_room_window1.Height = window_height
living_room_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(1000,2000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
living_room_window2 = doc.addObject("Part::Box","Living_Room_Window2")
living_room_window2.Length = window_width
living_room_window2.Width = 100
living_room_window2.Height = window_height
living_room_window2.Placement = FreeCAD.Placement(FreeCAD.Vector(4000,2000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bedroom1_window1 = doc.addObject("Part::Box","Bedroom1_Window1")
bedroom1_window1.Length = window_width
bedroom1_window1.Width = 100
bedroom1_window1.Height = window_height
bedroom1_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(8000,1000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bedroom1_window2 = doc.addObject("Part::Box","Bedroom1_Window2")
bedroom1_window2.Length = window_width
bedroom1_window2.Width = 100
bedroom1_window2.Height = window_height
bedroom1_window2.Placement = FreeCAD.Placement(FreeCAD.Vector(10000,1000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bedroom2_window1 = doc.addObject("Part::Box","Bedroom2_Window1")
bedroom2_window1.Length = window_width
bedroom2_window1.Width = 100
bedroom2_window1.Height = window_height
bedroom2_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(8000,5000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bedroom2_window2 = doc.addObject("Part::Box","Bedroom2_Window2")
bedroom2_window2.Length = window_width
bedroom2_window2.Width = 100
bedroom2_window2.Height = window_height
bedroom2_window2.Placement = FreeCAD.Placement(FreeCAD.Vector(10000,5000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
kitchen_window1 = doc.addObject("Part::Box","Kitchen_Window1")
kitchen_window1.Length = window_width
kitchen_window1.Width = 100
kitchen_window1.Height = window_height
kitchen_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(1000,8000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bathroom1_window1 = doc.addObject("Part::Box","Bathroom1_Window1")
bathroom1_window1.Length = window_width
bathroom1_window1.Width = 100
bathroom1_window1.Height = window_height
bathroom1_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(5500,1000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
bathroom2_window1 = doc.addObject("Part::Box","Bathroom2_Window1")
bathroom2_window1.Length = window_width
bathroom2_window1.Width = 100
bathroom2_window1.Height = window_height
bathroom2_window1.Placement = FreeCAD.Placement(FreeCAD.Vector(9500,5000,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
# Create doors
door_width = 1000
door_height = 2000
living_room_door1 = doc.addObject("Part::Box","Living_Room_Door1")
living_room_door1.Length = door_width
living_room_door1.Width = 100
living_room_door1.Height = door_height
living_room_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(3000,0,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
bedroom1_door1 = doc.addObject("Part::Box","Bedroom1_Door1")
bedroom1_door1.Length = door_width
bedroom1_door1.Width = 100
bedroom1_door1.Height = door_height
bedroom1_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(8000,0,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
bedroom2_door1 = doc.addObject("Part::Box","Bedroom2_Door1")
bedroom2_door1.Length = door_width
bedroom2_door1.Width = 100
bedroom2_door1.Height = door_height
bedroom2_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(8000,4000,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
kitchen_door1 = doc.addObject("Part::Box","Kitchen_Door1")
kitchen_door1.Length = door_width
kitchen_door1.Width = 100
kitchen_door1.Height = door_height
kitchen_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(0,7000,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
bathroom1_door1 = doc.addObject("Part::Box","Bathroom1_Door1")
bathroom1_door1.Length = door_width
bathroom1_door1.Width = 100
bathroom1_door1.Height = door_height
bathroom1_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(5000,0,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
bathroom2_door1 = doc.addObject("Part::Box","Bathroom2_Door1")
bathroom2_door1.Length = door_width
bathroom2_door1.Width = 100
bathroom2_door1.Height = door_height
bathroom2_door1.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,4000,floor_thickness+1000),FreeCAD.Rotation(0,0,0))
# Create balcony
balcony_length = 4000
balcony_width = 1000
balcony_height = 100
balcony = doc.addObject("Part::Box","Balcony")
balcony.Length = balcony_length
balcony.Width = balcony_width
balcony.Height = balcony_height
balcony.Placement = FreeCAD.Placement(FreeCAD.Vector(6000,0,floor_thickness+3000),FreeCAD.Rotation(0,0,0))
# Create sliding doors
sliding_door_width = 2000
sliding_door_height = 2000
sliding_door = doc.addObject("Part::Box","Sliding_Door")
sliding_door.Length = sliding_door_width
sliding_door.Width = 100
sliding_door.Height = sliding_door_height
sliding_door.Placement = FreeCAD.Placement(FreeCAD.Vector(6000,0,floor_thickness+1500),FreeCAD.Rotation(0,0,0))
# Create kitchen island
kitchen_island_length = 2000
kitchen_island_width = 1000
kitchen_island_height = 1000
kitchen_island = doc.addObject("Part::Box","Kitchen_Island")
kitchen_island.Length = kitchen_island_length
kitchen_island.Width = kitchen_island_width
kitchen_island.Height = kitchen_island_height
kitchen_island.Placement = FreeCAD.Placement(FreeCAD.Vector(1000,8000,floor_thickness),FreeCAD.Rotation(0,0,0))
# Create master bedroom ensuite
master_bedroom_ensuite_length = 2000
master_bedroom_ensuite_width = 2000
master_bedroom_ensuite_height = 3000
master_bedroom_ensuite = doc.addObject("Part::Box","Master_Bedroom_Ensuite")
master_bedroom_ensuite.Length = master_bedroom_ensuite_length
master_bedroom_ensuite.Width = master_bedroom_ensuite_width
master_bedroom_ensuite.Height = master_bedroom_ensuite_height
master_bedroom_ensuite.Placement = FreeCAD.Placement(FreeCAD.Vector(9000,0,floor_thickness),FreeCAD.Rotation(0,0,0))